### ISSUE TITLE
Backend reports modifiedDate in the request object

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#13]
For GET request:
Remote Address:50.16.227.214:443
Request URL:https://hidden-taiga-8809.herokuapp.com/request/10
Request Method:GET
Status Code:200 OK

Here is the returned object:
attachments: []
expertise_category: "general"
modificationDate: 1437207155585
response_age_group: "all"
response_gender: "any"
response_quantity: 5
response_wait_time: 1
status: "active"
text: "jopa-request"
time: 1437207155586
user_id: 6

It contains both modificationDate and time. Since modificationDate is not really supported on the server for PUT requests, an following attempt to update an object fails:
error: "Bad Request"
exception: "org.springframework.http.converter.HttpMessageNotReadableException"
message: "Could not read JSON: Unrecognized field "modificationDate" (class com.pisoft.asktheworld.data.ATWRequest), not marked as ignorable (9 known properties: "response_age_group", "response_quantity", "expertise_category", "text", "user_id", "attachments", "status", "response_wait_time", "response_gender"])↵ at [Source: org.apache.catalina.connector.CoyoteInputStream@2f14bfe9; line: 1, column: 237] (through reference chain: com.pisoft.asktheworld.data.ATWRequest["modificationDate"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "modificationDate" (class com.pisoft.asktheworld.data.ATWRequest), not marked as ignorable (9 known properties: "response_age_group", "response_quantity", "expertise_category", "text", "user_id", "attachments", "status", "response_wait_time", "response_gender"])↵ at [Source: org.apache.catalina.connector.CoyoteInputStream@2f14bfe9; line: 1, column: 237] (through reference chain: com.pisoft.asktheworld.data.ATWRequest["modificationDate"])"
status: 400

The exactly same problem applies to responses as well.

**Comment by shevalex** [comment]
modificationData is read only. You shouldn't send it in PUT request.

**Comment by aavtamon** [comment]
I don't want to have a logic that filters / processes the objects on the client. This way I will need to read the info coming from the server and copy it to a new object taking only specific fields. I don't think it is really a good idea. Why? It will be an extra work if we need to add a property later. I would need to change not only the code that works with the property but also two places in the backend communication layer (PUT/POST and GET) because I will have to copy properties from an internal objects to the one that I use in communication with server. 

Hence, I suggest you remove modifiedDate. If by some reason it is an automatic field that must be included, make it also accepted in all requests and just ignore then.
