### ISSUE TITLE
userId (user_id) must be ignored by the server is communicated back in a request

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#18]
Request: 
PUT ~/user/{userId}
{userId: 6, login: "antosha", password: "12345", languages: ["eng", "rus"], gender: "male",…}
age_category: "adult"
gender: "male"
incomingRequests: []
incomingRequestsIDs: []
languages: ["eng", "rus"]
login: "antosha"
name: "Antosha"
password: "12345"
userId: 6

Response:
error: "Bad Request"
exception: "org.springframework.http.converter.HttpMessageNotReadableException"
message: "Could not read JSON: Unrecognized field "userId" (class com.pisoft.asktheworld.data.ATWUser), not marked as ignorable (8 known properties: "gender", "login", "incomingRequests", "password", "name", "languages", "age_category", "incomingRequestsIDs"])↵ at [Source: org.apache.catalina.connector.CoyoteInputStream@2abe6b21; line: 1, column: 12] (through reference chain: com.pisoft.asktheworld.data.ATWUser["userId"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "userId" (class com.pisoft.asktheworld.data.ATWUser), not marked as ignorable (8 known properties: "gender", "login", "incomingRequests", "password", "name", "languages", "age_category", "incomingRequestsIDs"])↵ at [Source: org.apache.catalina.connector.CoyoteInputStream@2abe6b21; line: 1, column: 12] (through reference chain: com.pisoft.asktheworld.data.ATWUser["userId"])"
status: 400
timestamp: 1437324264783

**Comment by shevalex** [comment]
Now update does not throw error, but after update client stuck.

**Comment by aavtamon** [comment]
Fixed.
