### ISSUE TITLE
All User Preserence fields must be supported

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#19]
A server fails to update preferences:
error: "Bad Request"
exception: "org.springframework.http.converter.HttpMessageNotReadableException"
message: "Could not read JSON: Unrecognized field "expertises" (class com.pisoft.asktheworld.data.ATWUserSettings), not marked as ignorable (7 known properties: "inquiry_gender_preference", "inquiry_age_group_preference", "default_response_wait_time", "default_gender_preference", "default_response_age_group_preference", "default_response_quantity" [truncated]])↵ at [Source: org.apache.catalina.connector.CoyoteInputStream@2abe6b21; line: 1, column: 257] (through reference chain: com.pisoft.asktheworld.data.ATWUserSettings["expertises"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "expertises" (class com.pisoft.asktheworld.data.ATWUserSettings), not marked as ignorable (7 known properties: "inquiry_gender_preference", "inquiry_age_group_preference", "default_response_wait_time", "default_gender_preference", "default_response_age_group_preference", "default_response_quantity" [truncated]])↵ at [Source: org.apache.catalina.connector.CoyoteInputStream@2abe6b21; line: 1, column: 257] (through reference chain: com.pisoft.asktheworld.data.ATWUserSettings["expertises"])"
status: 400
timestamp: 1437324519636

API spec section 2.1.8 defines all fields that the server must support (both get and put)

**Comment by shevalex** [comment]
Is it fixed?

**Comment by aavtamon** [comment]
No. Did you count for a magic :)?

Remote Address:54.83.200.118:443
Request URL:https://hidden-taiga-8809.herokuapp.com/user/undefined/settings
Request Method:PUT
Status Code:400 Bad Request
Response Headers
view source
Access-Control-Allow-Headers:x-requested-with, Content-Type, Location, Allow, Token
Access-Control-Allow-Methods:POST, GET, OPTIONS, DELETE, PUT
Access-Control-Allow-Origin:*
Access-Control-Expose-Headers:Location
Access-Control-Max-Age:3600
Cache-Control:no-cache, no-store, max-age=0, must-revalidate
Cache-Control:no-cache, no-store, max-age=0, must-revalidate
Connection:keep-alive
Content-Type:application/json;charset=UTF-8
Date:Fri, 24 Jul 2015 19:46:05 GMT
Expires:0
Expires:0
Pragma:no-cache
Pragma:no-cache
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked
Via:1.1 vegur
X-Content-Type-Options:nosniff
X-Content-Type-Options:nosniff
X-Frame-Options:DENY
X-Frame-Options:DENY
X-Xss-Protection:1; mode=block
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,ru;q=0.6
Connection:keep-alive
Content-Length:337
content-type:application/json
Host:hidden-taiga-8809.herokuapp.com
Origin:http://localhost
Referer:http://localhost/atw/main.html
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36
Request Payload
view source
{default_response_quantity: 5, default_response_wait_time: 1,…}
contact_info: ""
contact_info_requestable: false
contact_name: ""
default_gender_preference: "all"
default_response_age_group_preference: "all"
default_response_quantity: 5
default_response_wait_time: 1
expertises: ["general"]
inquiry_age_group_preference: "all"
inquiry_gender_preference: "all"
inquiry_quantity_per_day: -1


Response details:
error: "Bad Request"
exception: "org.springframework.beans.TypeMismatchException"
message: "Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: "undefined""
status: 400
timestamp: 1437767165796

**Comment by aavtamon** [comment]
It works today all right. Not sure what the problem was.
