### ISSUE TITLE
User settings (preferences) report incorrect values

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#21]
GET ~/user/{user id}/settings

Response:
{
default_gender_preference: null
default_response_age_group_preference: null
default_response_quantity: 5
default_response_wait_time: 1
inquiry_age_group_preference: null
inquiry_gender_preference: "any"
inquiry_quantity_per_day: 5
}

There must be no nulls reported back.

**Comment by aavtamon** [comment]
Your defaults should be:
default_gender_preference: "any"
default_response_age_group_preference: "all"
inquiry_age_group_preference: "all"

**Comment by shevalex** [comment]
As we discussed all default values will be "all" instead of any.

**Comment by aavtamon** [comment]
It still does not work. I also don't think that you re-created the database

This is what I see from the server during login:
contact_info: null
contact_info_requestable: false
contact_name: null
default_gender_preference: null
default_response_age_group_preference: "all"
default_response_quantity: 5
default_response_wait_time: 1
expertises: null
inquiry_age_group_preference: null
inquiry_gender_preference: "any"
inquiry_quantity_per_day: 5

A lot of nulls. You also wanted to change any to all which I believe you did not.

**Comment by aavtamon** [comment]
retested with the latest server by creating a new user.
Much better, but still see one one null for expertises.

Here are the expertises enumeration (for now)
general, law, medicine, construction. 
General must be the default value assigned during account creation.

**Comment by shevalex** [comment]
А какой я тебе должен экспертиз сделать?

**Comment by aavtamon** [comment]
Verified
