### ISSUE TITLE
New user cannot be created

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#22]
I tested it yesterday and it worked. It gets broken after your last commit:

POST ~/user  to create a new user fails with 400 Bad request

Remote Address:23.21.193.37:443
Request URL:https://hidden-taiga-8809.herokuapp.com/user
Request Method:POST
Status Code:400 Bad Request
Response Headers
view source
Access-Control-Allow-Headers:x-requested-with, Content-Type, Location, Allow, Token
Access-Control-Allow-Methods:POST, GET, OPTIONS, DELETE, PUT
Access-Control-Allow-Origin:*
Access-Control-Expose-Headers:Location
Access-Control-Max-Age:3600
Connection:keep-alive
Date:Mon, 20 Jul 2015 08:48:40 GMT
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked
Via:1.1 vegur
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,ru;q=0.6
Connection:keep-alive
Content-Length:114
content-type:application/json
Host:hidden-taiga-8809.herokuapp.com
Origin:null
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36
Request Payload
view source
{login: "XXX", password: "12345", name: "XxX", gender: "female", languages: ["eng", "rus"],…}
age_category: "child"
gender: "female"
languages: ["eng", "rus"]
login: "XXX"
name: "XxX"
password: "12345"

**Comment by shevalex** [comment]
Is this still true?

**Comment by aavtamon** [comment]
User creation works the latest server
