### ISSUE TITLE
Wrong GENDER_PREFERENCE male/female index in application.js

### ISSUE THREAD

**Issue by shevalex** [shevalex/asktheworld#25]
Male index 2

            if (ageCategory == this.AGE_CATEGORY_PREFERENCE[0].data) {
                if (gender == this.GENDER_PREFERENCE[0].data) {
                    return I18n.getLocale().literals.TargetGroupAll;
                } else if (gender == this.GENDER_PREFERENCE[1].data) {
                    return I18n.getLocale().literals.TargetGroupAllMen;
                } else if (gender == this.GENDER_PREFERENCE[2].data) {
                    return I18n.getLocale().literals.TargetGroupAllWomen;
                }
            } else if (ageCategory == this.AGE_CATEGORY_PREFERENCE[1].data) {
                if (gender == this.GENDER_PREFERENCE[0].data) {
                    return I18n.getLocale().literals.TargetGroupAllChildren;
                } else if (gender == this.GENDER_PREFERENCE[1].data) {
                    return I18n.getLocale().literals.TargetGroupAllBoys;
                } else if (gender == this.GENDER_PREFERENCE[2].data) {
                    return I18n.getLocale().literals.TargetGroupAllGirls;
                }
            } else if (ageCategory == this.AGE_CATEGORY_PREFERENCE[2].data) {
                if (gender == this.GENDER_PREFERENCE[0].data) {
                    return I18n.getLocale().literals.TargetGroupAllTeenagers;
                } else if (gender == this.GENDER_PREFERENCE[1].data) {
                    return I18n.getLocale().literals.TargetGroupAllTeenBoys;
                } else if (gender == this.GENDER_PREFERENCE[2].data) {
                    return I18n.getLocale().literals.TargetGroupAllTeenGirls;
                }
            } else if (ageCategory == this.AGE_CATEGORY_PREFERENCE[3].data) {
                if (gender == this.GENDER_PREFERENCE[0].data) {
                    return I18n.getLocale().literals.TargetGroupAllYoungs;
                } else if (gender == this.GENDER_PREFERENCE[1].data) {
                    return I18n.getLocale().literals.TargetGroupAllYoungMen;
                } else if (gender == this.GENDER_PREFERENCE[2].data) {
                    return I18n.getLocale().literals.TargetGroupAllYoungWomen;
                }
            } else if (ageCategory == this.AGE_CATEGORY_PREFERENCE[4].data) {
                if (gender == this.GENDER_PREFERENCE[0].data) {
                    return I18n.getLocale().literals.TargetGroupAllAdults;
                } else if (gender == this.GENDER_PREFERENCE[1].data) {
                    return I18n.getLocale().literals.TargetGroupAllAdultMen;
                } else if (gender == this.GENDER_PREFERENCE[2].data) {
                    return I18n.getLocale().literals.TargetGroupAllAdultWomen;
                }
            } else if (ageCategory == this.AGE_CATEGORY_PREFERENCE[5].data) {
                if (gender == this.GENDER_PREFERENCE[0].data) {
                    return I18n.getLocale().literals.TargetGroupAllSeniors;
                } else if (gender == this.GENDER_PREFERENCE[1].data) {
                    return I18n.getLocale().literals.TargetGroupAllSeniorMen;
                } else if (gender == this.GENDER_PREFERENCE[2].data) {
                    return I18n.getLocale().literals.TargetGroupAllSeniorWomen;
                }
            }

**Comment by aavtamon** [comment]
Can you  be a bit more verbose? I don't see anything wrong in the code you cited...

**Comment by aavtamon** [comment]
Fixed.
