### ISSUE TITLE
When response is asked to update the status it is not taking affect

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#26]
An update request with 'status': "viewed" does not take an affect:
when pulled back the response still say 'unviewed'. Similarly, the structure of incoming/outgoing response does not change - it should move from unviewed to viewed array

**Comment by shevalex** [comment]
Bliaaaaa

**Comment by aavtamon** [comment]
I am verifying this specific one because now the update does seem to take an effect.
However I reported another CR, https://github.com/shevalex/asktheworld/issues/27. The updated response is never reported back.
