### ISSUE TITLE
After a response is marked read it is never reported back

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#27]
User case:
User 1:
  Create a request

User 2:
   Re-login. Read this request and provide a response

User 1:
   Re-login. See the response and mark it read (click it)

User 2:
   Re-login. See that the response was read (white header)

User 1:
   Re-login again. Check all requests. See that they all report 0/0 for responses.
The result of the request to get responses returns empty lists:

https://hidden-taiga-8809.herokuapp.com/user/3/responses/incoming/11?status=unviewed
Response:
unviewed: []
viewed: []

**Comment by shevalex** [comment]
There are no unviewed response on 11 request.
https://hidden-taiga-8809.herokuapp.com/user/3/responses/incoming/11?status=unviewed
{"viewed":[],"unviewed":[]}
https://hidden-taiga-8809.herokuapp.com/user/3/responses/incoming/11?status=viewed
{"viewed":[12],"unviewed":[]}
https://hidden-taiga-8809.herokuapp.com/user/3/responses/incoming/11?status=all
{"viewed":[12],"unviewed":[]}

I don't see any problem.

**Comment by aavtamon** [comment]
I believe the problem is with you returning empty arrays.
I can temporary hack the client code to ignore an array that was not requested. However the contract should be that you either report both viewed and unviewed correctly OR you only report one (the other one should be either omitted or be null). Empty array indicates that it is a proper value and there are no responses.

**Comment by aavtamon** [comment]
Specifically, this is what should be in reported:
https://hidden-taiga-8809.herokuapp.com/user/3/responses/incoming/11?status=unviewed
{"unviewed":[]}
OR
{"viewed":null,"unviewed":[]}

https://hidden-taiga-8809.herokuapp.com/user/3/responses/incoming/11?status=viewed
{"viewed":[]}
OR
{"viewed":[],"unviewed":null}

https://hidden-taiga-8809.herokuapp.com/user/3/responses/incoming/11?status=all
{"viewed":[],"unviewed":[]}

**Comment by aavtamon** [comment]
Specifically, this is what should be in reported:
https://hidden-taiga-8809.herokuapp.com/user/3/responses/incoming/11?status=unviewed
{"unviewed":[]}
OR
{"viewed":null,"unviewed":[]}

https://hidden-taiga-8809.herokuapp.com/user/3/responses/incoming/11?status=viewed
{"viewed":[]}
OR
{"viewed":[],"unviewed":null}

https://hidden-taiga-8809.herokuapp.com/user/3/responses/incoming/11?status=all
{"viewed":[],"unviewed":[]}
