### ISSUE TITLE
Deletion of the incoming response fails

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#28]
A request to delete (remove from the incoming list) of the incoming response fails with 500 error

Remote Address:23.21.197.144:443
Request URL:https://hidden-taiga-8809.herokuapp.com/user/3/responses/incoming/12
Request Method:DELETE
Status Code:500 Internal Server Error
Response Headers
view source
Access-Control-Allow-Headers:x-requested-with, Content-Type, Location, Allow, Token
Access-Control-Allow-Methods:POST, GET, OPTIONS, DELETE, PUT
Access-Control-Allow-Origin:*
Access-Control-Expose-Headers:Location
Access-Control-Max-Age:3600
Cache-Control:no-cache, no-store, max-age=0, must-revalidate
Connection:keep-alive
Content-Type:application/json;charset=UTF-8
Date:Sat, 25 Jul 2015 18:09:04 GMT
Expires:0
Pragma:no-cache
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked
Via:1.1 vegur
X-Content-Type-Options:nosniff
X-Frame-Options:DENY
X-Xss-Protection:1; mode=block
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,ru;q=0.6
Connection:keep-alive
Content-Length:0
content-type:application/json
Host:hidden-taiga-8809.herokuapp.com
Origin:http://localhost
Referer:http://localhost/atw/main.html
Token:antosha:12345
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36

Response:
error: "Internal Server Error"
exception: "org.springframework.dao.InvalidDataAccessApiUsageException"
message: "Not allowed to create transaction on shared EntityManager - use Spring transactions or EJB CMT instead; nested exception is java.lang.IllegalStateException: Not allowed to create transaction on shared EntityManager - use Spring transactions or EJB CMT instead"
status: 500
timestamp: 1437847744820

**Comment by shevalex** [comment]
should be fixed

**Comment by aavtamon** [comment]
Yes, resolved
