### ISSUE TITLE
Web: Response is not considered read after clicked

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#30]
The counter on the Outgoing Request Details page remains unchanged and the request remains in the Dashboard after the response is clicked (marked read)

**Comment by aavtamon** [comment]
The root cause of the issue is that change in response status does NOT produce an INCOMING_RESPONSES_CHANGED event.
Please make sure that change in status for requests and responses produces both REQUEST (RESPONSE) CHANGED event as well as a corresponding 'list changed' event

**Comment by shevalex** [comment]
What is request data changed when user clicks on response?

**Comment by aavtamon** [comment]
The "status" property is changed from unviewed to viewed.
You DO generate a response_changed event:
{"events":[{"request_id":65,"response_id":66,"type":"RESPONSE_CHANGED"}],"timestamp":1442082101686}

But you don't generate INCOMING_RESPONSES_CHANGED event that you should because the lists in the 'responses' structure change - a response moves from unviewed to viewed.

**Comment by shevalex** [comment]
from spec:
INCOMING_RESPONSES_CHANGED
		The event is produced when a server routes to the client a new response or otherwise turns the previously routed response off.

**Comment by aavtamon** [comment]
Whatever is written in the spec - when a relation is changed, the corresponding 'relation changed' event should be generated. If an event body carries an information that is changed, an event should be generated. If a response changes its status, your {viewed, unviewed} objects on the event becomes different. I can probably work it around on the client if it is really have to, but it needs to be addressed on the server

**Comment by shevalex** [comment]
should be fixed now
