### ISSUE TITLE
Web: inquiries that cannot be responded should not be listed on Dashboard

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#32]

**Comment by aavtamon** [comment]
The root cause is that the status of the inquires is not changed in inactive when they expire. The server should change the status.
However I am not sure what is the right moment for the server to perform the check. Apparently the server can do a check when it returns a list of objects (inquires or requests or responses) and change the status of the objects as it builds the response. However it does not answer the question how to detect the expiration dynamically to produce an event. We can discuss

**Comment by shevalex** [comment]
I think on event request we can check if request has expired too.

**Comment by aavtamon** [comment]
We can try. It could be too much checking for the server on a request that happens non-stop.

**Comment by shevalex** [comment]
As you understand we don't have a server thread that checks status, creates
events and etc. Everything is doing during request processing.

**Comment by aavtamon** [comment]
Yes. There is one more alternative though... We could do it on the client side and let the client update the status as needed.

**Comment by shevalex** [comment]
should work now. Server updates status of expired events and creates event is status was changed.

**Comment by aavtamon** [comment]
Nope, I don't see it working.
When the time comes, I receive REQUEST_CHANGED event:

{events: [{request_id: 11, type: "REQUEST_CHANGED"}], timestamp: 1443977473336}

When UI re-pulls the request in response to this event it does see it inactive:
{
attachments: []
expertise_category: "general"
id: 11
response_age_group: "all"
response_gender: "all"
response_quantity: 5
response_wait_time: 1
status: "inactive"
text: "Test2"
time: 1443973872471
user_id: 4
}

However no INCOMING_REQUESTS_CHANGED event is coming.

**Comment by shevalex** [comment]
Fixed in ver 21.
