### ISSUE TITLE
Server: PUT request should maintain the original values for all properties that are not mentioned in the PUT request

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#35]
A PUT request to update a request carries back a JSON object with {"time": "<null>"} value

**Comment by aavtamon** [comment]
A little deeper investigation indicates that the server expects a client to provide TIME and keeps it. The expected behavior is that the server keeps the current value for any property that is not present in the update (PUT) request

**Comment by shevalex** [comment]
what do you mean by "the server expects a client to provide TIME and keeps it"?

this body for put request does not have time
{
    "user_id": 1,
    "text": "Тест статус ардэйт8",
    "attachments": [],
    "response_quantity": 5,
    "response_wait_time": 100,
    "response_age_group": "all",
    "response_gender": "all",
    "status": "active",
    "expertise_category": "general"
}

and works fine

**Comment by aavtamon** [comment]
*Request*: PUT request/67
{
attachments: []
expertise_category: "general"
id: 67
response_age_group: "all"
response_gender: "all"
response_quantity: -1
response_wait_time: 168
status: "active"
text: "aaaaaaab"
time: null
user_id: 3
}
Note that time is set to null.


Here is the response to this request:
{"user_id":3,"text":"aaaaaaab","attachments":[],"response_quantity":-1,"response_wait_time":168,"response_age_group":"all","response_gender":"all","status":"active","expertise_category":"general","id":67,"time":null}

Note that time property is 'echoed' as null. It should not. It should be ingored in the input and reported back as appropriate (whatever is stored on the server)

**Comment by shevalex** [comment]
Ok, will check.
