### ISSUE TITLE
Server: when pulled every second, events are often lost

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#36]
With IOS client pulling events every seconds frequently results in event loss.

Interestingly, it is not observed with Web client (set for the same 1 second interval re-pulling)

**Comment by shevalex** [comment]
I need logs or something like that.
Or at least a steps to reproduce

**Comment by aavtamon** [comment]
Yes, I essentially logged it just to keep track of the issue. I can get you a parallel log from a web client and IOS client if you think it is going to help. Will it? Does the log with the timestamps be good eough for you to figure out why events can be lost?

**Comment by aavtamon** [comment]
Web log
{"events":[],"timestamp":1441421811423}
backend.js:1052 {"events":[],"timestamp":1441421812663}
backend.js:1052 {"events":[],"timestamp":1441421813843}
backend.js:1052 {"events":[],"timestamp":1441421815040}
backend.js:1052 {"events":[],"timestamp":1441421816253}
backend.js:1052 {"events":[],"timestamp":1441421817450}
backend.js:1052 {"events":[],"timestamp":1441421818663}
backend.js:1052 {"events":[],"timestamp":1441421819870}
backend.js:1052 {"events":[],"timestamp":1441421821093}
backend.js:1052 {"events":[],"timestamp":1441421822308}
backend.js:1052 {"events":[{"request_ids":null,"type":"INCOMING_REQUESTS_CHANGED"},{"request_id":62,"type":"REQUEST_CHANGED"}],"timestamp":1441421823528}
backend.js:1052 {"events":[],"timestamp":1441421824703}
backend.js:1052 {"events":[],"timestamp":1441421825900}
backend.js:1052 {"events":[],"timestamp":1441421827105}
backend.js:1052 {"events":[],"timestamp":1441421828305}
backend.js:1052 {"events":[],"timestamp":1441421829493}
backend.js:1052 {"events":[],"timestamp":1441421830672}


IOS log for the same moment
{
    events =     (
    );
    timestamp = 1441421812969;
}
{
    events =     (
    );
    timestamp = 1441421814103;
}
{
    events =     (
    );
    timestamp = 1441421815230;
}
{
    events =     (
    );
    timestamp = 1441421816359;
}
{
    events =     (
    );
    timestamp = 1441421817504;
}
{
    events =     (
    );
    timestamp = 1441421818637;
}
{
    events =     (
    );
    timestamp = 1441421819794;
}
{
    events =     (
    );
    timestamp = 1441421820934;
}
{
    events =     (
    );
    timestamp = 1441421822111;
}
{
    events =     (
    );
    timestamp = 1441421823259;
}
{
    events =     (
    );
    timestamp = 1441421824414;
}
{
    events =     (
    );
    timestamp = 1441421825553;
}
{
    events =     (
    );
    timestamp = 1441421826719;
}
{
    events =     (
    );
    timestamp = 1441421827856;
}
{
    events =     (
    );
    timestamp = 1441421828990;
}
{
    events =     (
    );
    timestamp = 1441421830120;
}
{
    events =     (
    );
    timestamp = 1441421831253;
}

**Comment by aavtamon** [comment]
However, I did notice this time that events in Web are also lost (Not delivered)

**Comment by shevalex** [comment]
Do not see steps to reproduce.
Can it be related to ticket #26?

**Comment by aavtamon** [comment]
The best is probably use the web application. Use two sessions (user 1 and user 2). Change something as user 1 and you will see that user 2 is not always getting it. I gave you enough logs to see that for the same period, one client (web) got an event and the other client - iOS - missed it.
It is really not about ios vs web - the events are missing in the web clients too.

**Comment by aavtamon** [comment]
I need this fix for event distribution. Then I think we will be good to deliver all integration changes back to master

**Comment by shevalex** [comment]
Should be fixed in ver 0.13

**Comment by aavtamon** [comment]
I don't see it fixed. Events are still lost
