### ISSUE TITLE
Server: response creation is denied

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#38]
From iOS:

POST ~/response
post Body = {
    "age_category" = adult;
    "contact_info_status" = no;
    gender = male;
    requestId = 49;
    status = unviewed;
    text = yyyy;
    time = 0;
    userId = 3;
}

Response Status = 400

**Comment by shevalex** [comment]
Is this fixed now?

**Comment by aavtamon** [comment]
NO. I still see 400 Bad Request

**Comment by aavtamon** [comment]
Here is the request body:
{
age_category: "adult"
attachments: []
contact_info_status: "no"
gender: "male"
request_id: "5"
text: "Response-1"
user_id: 2
}

**Comment by aavtamon** [comment]
Found and fixed a bug in web implementation that kept request_id a string.
Still, with the new body the same 400 Bad Request

age_category: "adult"
attachments: []
contact_info_status: "no"
gender: "male"
request_id: 5
text: "Response-1"
user_id: 2

**Comment by shevalex** [comment]
Should be fixed now. Please test.

**Comment by aavtamon** [comment]
Yes, fixed now
