### ISSUE TITLE
Server: time is reported NULL is response to a PUT request

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#42]
Updating a response:

PUT
{
age_category: "adult"
attachments: []
contact_info_status: "no"
gender: "male"
id: 15
request_id: 14
star_rating: 0
status: "viewed"
text: "Response3"
time: 1442630648709
user_id: 9
}

Response from the server:
{user_id: 9, request_id: 14, text: "Response3", attachments: [], contact_info_status: "no",…}
age_category: "adult"
attachments: []
contact_info_status: "no"
gender: "male"
id: 15
request_id: 14
star_rating: 0
status: "viewed"
text: "Response3"
time: null
user_id: 9
}

Note "time: null" in the report-back message.

**Comment by aavtamon** [comment]
As usual, you should ignore time in the incoming request, it may or may not be correct, but you need to overwrite it anyway.

**Comment by shevalex** [comment]
Do you need to have time in Respose object? I can remove it.

**Comment by aavtamon** [comment]
You should report full state of the created/modified object. We can change the client if there is a solid reason why not, but this is the current client's expectation. You need to report it in POST anyway. It should be no reasons not to report in PUT. Besides, we may want to report both creation time and modification time eventually.

**Comment by shevalex** [comment]
We have both field create and modify date. Do you want to to report them both?

**Comment by shevalex** [comment]
Should be fixed in ver 0.16
