### ISSUE TITLE
Server: latest release broke event delivery

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#44]
REQUEST:
GET https://hidden-taiga-8809.herokuapp.com/events/user/3?timestamp=1443840770607

timestamp: 1443840788382, status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
exception: "org.springframework.dao.InvalidDataAccessApiUsageException"
message: "node to traverse cannot be null!; nested exception is java.lang.IllegalArgumentException: node to traverse cannot be null!"
status: 500
timestamp: 1443840788382

{"timestamp":1443840788382,"status":500,"error":"Internal Server Error","exception":"org.springframework.dao.InvalidDataAccessApiUsageException","message":"node to traverse cannot be null!; nested exception is java.lang.IllegalArgumentException: node to traverse cannot be null!"}

**Comment by shevalex** [comment]
Should be fixed in version 20 (loaded on server, not checked in yet)

**Comment by shevalex** [comment]
Please, try on server
