### ISSUE TITLE
Server: a new api is required to provide account-specific global settings

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#51]
For a given user account, the server should report:
1. A list of supported categories
2. For each category, the list should include:
   - display representation
   - data representation
   - text color
   - background color

Something like:

GET /user/{user id}/settings/categories

response:
{ "categories": [ {"data": "medical", "display": "Medical", "bg": "ff5544", "fg": "220189"}, {...}]}

**Comment by aavtamon** [comment]
Specifically we need to:
1. Rename user/{user id}/settings to user/{user id}/preferences
2. Introduce user/{user id}/settings that only supports GET and currently reports:
{
 { "expertise_categories": [ {"data": "medical", "display": "Medical", "bg": "ff5544", "fg": "220189"}, {...}]}
}

**Comment by aavtamon** [comment]
Currently the server should report the following output for settings:
{expertise_categories: [ 
    {data: "general", display: "General", bg: "gray", fg: "black"},
    {data: "law", display: "Law", bg: "green", fg: "black"},
    {data: "medicine", display: "Medical", bg: "red", fg: "black"},
    {data: "construction", display: "Construction", bg: "blue", fg: "black"}
  ]}

**Comment by shevalex** [comment]
Is this list of objects specific to every user? 
Are we going to perform any operations on this object on server side? 
How do we modify this list?

**Comment by shevalex** [comment]
version 0.1.5s

**Comment by aavtamon** [comment]
I don't see it working:

Remote Address:50.16.200.158:443
Request URL:https://hidden-taiga-8809.herokuapp.com/user/3/settings
Request Method:GET
Status Code:400 Bad Request


Details:
error: "Bad Request"
exception: "org.springframework.web.bind.ServletRequestBindingException"
message: "Missing URI template variable 'userID' for method parameter of type int"
status: 400
timestamp: 1447105698443
