### ISSUE TITLE
Server: password recovery should be supported

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#59]
GET user/?reset=<user login> 
should result in sending out an email with the link to reset password.
Clicking on the link in the email should take the user to the password reset page.

**Comment by aavtamon** [comment]
The format of the link should be the following:
file:///Users/aavtamonov/project/asktheworld/web/index.html#[page-RestorePasswordPage]:[recoveryToken-unique token here]

**Comment by aavtamon** [comment]
We need a server api to request password reset (the link in email). Should be 
GET user?request_password_recovery=" + login
OR we need to resolve the user id by login first and then be based on the user id?

We also need an api to recover password. Not sure what is the best api. Maybe
PUT user/{user id}/reset_password

Let's discuss

**Comment by aavtamon** [comment]
The api implemented in the UI:
1. Request password recovery
    * GET user?request_password_recovery=<login>
    * no authentication header
    * Expected response: 200 OK  if the login was found and an email sent. 404 Not Found if login is not detected

2. Set new password
    * PUT user?recovery_token=<recoveryToken> &password_recovery=<login>
    * no authentication header
    * Expected response: 200 OK if the password is set alright. 403 Forbidden if the provided token does not match or is expired. 404 Not Found if login is not found.

**Comment by shevalex** [comment]
let's use:
1. GET user/reset?login=login to get token
2. PUT user/reset?login=login&token=token&passwod=password
