### ISSUE TITLE
Server: an API to get contact info should be provided

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#62]
The currently proposed api is
response/{responseId}?contactinfo

The expected behavior is that the requester receives an updated Response object with an extra field "contact_info" in the following format:
{contact_name: "XXX", contact_info: "(123) 456-78-90"}

When the request is processed, the "contact_info_status" of the response should change from "can_provide" to "provided" persistently.
If it is "provided" a request to get a response object should come with the contact_info field right away.
When it is first requested, a response change event should be produced.

**Comment by shevalex** [comment]
what is XXX in contact name?

**Comment by shevalex** [comment]
What should be returned if contact info is not requestable?

**Comment by aavtamon** [comment]
You can either return an error (say 403) or just the original response without contact info and with the contact_info_status that as before indicates 'not_available'

**Comment by aavtamon** [comment]
Here is the proposed change to api:
response/{responseId}?paid=contact_info

This is needed to more consistently support other paid information that a response may provide

**Comment by aavtamon** [comment]
The following should be provided for each 'paid' response field.
If a field is named xxx, then:
xxx_status = {"not_available" | "can_provide" | "provided" }
xxx_pay_policy = {"free", "paid"} // it can be more policies in the future, maybe even pay amount. For now - just one of those two redefined strings
xxx itself

The field is only available in the body of the response if xxx_status is "provided". 
Status becomes provided after it was at least once requested by the request's user via
GET response/{responseId}?paid=xxx

**Comment by aavtamon** [comment]
We will also need some adjustments in the user preferences that I am not yet certain about

**Comment by aavtamon** [comment]
The final format:
1. For response:
response = {
    paid_features: {
      hidden_text: {
        status: ["not_available" | "can_provide" | "provided"],
        policy: <string>,
        data: {text: <text>}
      },
      contact_info: {
        status: ["not_available" | "can_provide" | "provided"],
        policy: <string>,
        data: {contact_name: <name>, contact_info: <info>}
      }
    }
}

User Preferences:
{
  paid_features: {
    hidden_text: {
      enabled: true | false,
      policy: <string>,
      data: {}
    },
    
    contact_info: {
      enabled: true | false,
      policy: <string>,
      data: {contact_name: <string>, contact_information: <string>}
    }
  }
}
