### ISSUE TITLE
Server: hidden text should be provided

### ISSUE THREAD

**Issue by aavtamon** [shevalex/asktheworld#64]
Similar to contact_info, the following should be supported:

hidden_text_status = {"not_available" | "can_provide" | "provided" }
hidden_text_pay_policy = {"free", "paid"} // it can be more policies in the future, maybe even pay amount. Now it is just a predefined string 
hidden_text - a string

hidden_text is set by the responser. hidden_text_status can come from a client but could also be fully managed by a server basing on the hidden_text. If it is not provided then the status is 'not_available', otherwise it is 'can_provide' unless it was requested.

The request to provide is GET response/{responseId}?paid=hidden_text

**Comment by shevalex** [comment]
Fixed?
